version: "3.4"
services:
  hardhat_examples:
    build:
      context: ${HARDHAT_EXAMPLES_BUILD_CONTEXT}
    image: ${HARDHAT_EXAMPLES_IMAGE}
    command: node scripts/integration-test.js
    tty: true
    stdin_open: true
    networks:
      - reef-explorer-dev-prod_reefscan

networks:
  reef-explorer-dev-prod_reefscan:
    external: true
    driver: bridge