- table:
    schema: public
    name: account
  select_permissions:
  - role: public
    permission:
      columns:
      - account_id
      - identity
      - identity_display
      - identity_display_parent
      - balances
      - available_balance
      - free_balance
      - locked_balance
      - nonce
      - timestamp
      - block_height
      - evm_address
      filter: {}
      allow_aggregations: true
- table:
    schema: public
    name: block
  select_permissions:
  - role: public
    permission:
      columns:
      - block_number
      - finalized
      - block_author
      - block_author_name
      - block_hash
      - parent_hash
      - extrinsics_root
      - state_root
      - active_era
      - current_index
      - is_election
      - spec_name
      - spec_version
      - total_events
      - total_extrinsics
      - total_issuance
      - timestamp
      filter: {}
      allow_aggregations: true
- table:
    schema: public
    name: contract
  array_relationships:
  - name: holders
    using:
      manual_configuration:
        remote_table:
          schema: public
          name: token_holder
        column_mapping:
          contract_id: contract_id
  select_permissions:
  - role: public
    permission:
      columns:
      - contract_id
      - name
      - bytecode
      - arguments
      - value
      - gas_limit
      - storage_limit
      - signer
      - block_height
      - verified
      - source
      - compiler_version
      - optimization
      - runs
      - target
      - abi
      - license
      - is_erc20
      - token_name
      - token_symbol
      - token_decimals
      - token_total_supply
      - token_validated
      - token_description
      - token_icon_url
      - token_coingecko_id
      - token_coinmarketcap_id
      - timestamp
      filter: {}
      allow_aggregations: true
- table:
    schema: public
    name: contract_verification_request
  select_permissions:
  - role: public
    permission:
      columns:
      - id
      - contract_id
      - source
      - filename
      - compiler_version
      - arguments
      - optimization
      - runs
      - target
      - license
      - status
      - error_type
      - error_message
      - timestamp
      filter: {}
      allow_aggregations: true
- table:
    schema: public
    name: era_commission
  select_permissions:
  - role: public
    permission:
      columns:
      - stash_address
      - era
      - commission
      filter: {}
      allow_aggregations: true
- table:
    schema: public
    name: era_commission_avg
  select_permissions:
  - role: public
    permission:
      columns:
      - era
      - commission_avg
      filter: {}
      allow_aggregations: true
- table:
    schema: public
    name: era_points
  select_permissions:
  - role: public
    permission:
      columns:
      - stash_address
      - era
      - points
      filter: {}
      allow_aggregations: true
- table:
    schema: public
    name: era_points_avg
  select_permissions:
  - role: public
    permission:
      columns:
      - era
      - points_avg
      filter: {}
      allow_aggregations: true
- table:
    schema: public
    name: era_relative_performance
  select_permissions:
  - role: public
    permission:
      columns:
      - stash_address
      - era
      - relative_performance
      filter: {}
      allow_aggregations: true
- table:
    schema: public
    name: era_relative_performance_avg
  select_permissions:
  - role: public
    permission:
      columns:
      - era
      - relative_performance_avg
      filter: {}
      allow_aggregations: true
- table:
    schema: public
    name: era_self_stake
  select_permissions:
  - role: public
    permission:
      columns:
      - stash_address
      - era
      - self_stake
      filter: {}
      allow_aggregations: true
- table:
    schema: public
    name: era_self_stake_avg
  select_permissions:
  - role: public
    permission:
      columns:
      - era
      - self_stake_avg
      filter: {}
      allow_aggregations: true
- table:
    schema: public
    name: era_vrc_score
  select_permissions:
  - role: public
    permission:
      columns:
      - stash_address
      - era
      - vrc_score
      filter: {}
      allow_aggregations: true
- table:
    schema: public
    name: event
  select_permissions:
  - role: public
    permission:
      columns:
      - block_number
      - event_index
      - section
      - method
      - phase
      - data
      - timestamp
      filter: {}
      allow_aggregations: true
- table:
    schema: public
    name: extrinsic
  select_permissions:
  - role: public
    permission:
      columns:
      - block_number
      - extrinsic_index
      - is_signed
      - signer
      - section
      - method
      - args
      - hash
      - doc
      - fee_info
      - fee_details
      - success
      - timestamp
      filter: {}
      allow_aggregations: true
- table:
    schema: public
    name: harvest_error
  select_permissions:
  - role: public
    permission:
      columns:
      - block_number
      - error
      - timestamp
      filter: {}
      allow_aggregations: true
- table:
    schema: public
    name: log
  select_permissions:
  - role: public
    permission:
      columns:
      - block_number
      - log_index
      - type
      - engine
      - data
      - timestamp
      filter: {}
      allow_aggregations: true
- table:
    schema: public
    name: ranking
  select_permissions:
  - role: public
    permission:
      columns:
      - block_height
      - rank
      - active
      - active_rating
      - name
      - identity
      - has_sub_identity
      - sub_accounts_rating
      - verified_identity
      - identity_rating
      - stash_address
      - stash_address_creation_block
      - stash_parent_address_creation_block
      - address_creation_rating
      - controller_address
      - part_of_cluster
      - cluster_name
      - cluster_members
      - show_cluster_member
      - nominators
      - nominators_rating
      - commission
      - commission_history
      - commission_rating
      - active_eras
      - era_points_history
      - era_points_percent
      - era_points_rating
      - performance
      - performance_history
      - relative_performance
      - relative_performance_history
      - slashed
      - slash_rating
      - slashes
      - payout_history
      - payout_rating
      - self_stake
      - other_stake
      - total_stake
      - stake_history
      - total_rating
      - dominated
      - timestamp
      filter: {}
      allow_aggregations: true
- table:
    schema: public
    name: signed_extrinsic
  select_permissions:
  - role: public
    permission:
      columns:
      - block_number
      - extrinsic_index
      - signer
      - section
      - method
      - args
      - hash
      - doc
      - fee_info
      - fee_details
      - success
      - timestamp
      filter: {}
      allow_aggregations: true
- table:
    schema: public
    name: staking_reward
  select_permissions:
  - role: public
    permission:
      columns:
      - block_number
      - event_index
      - account_id
      - amount
      - timestamp
      filter: {}
      allow_aggregations: true
- table:
    schema: public
    name: staking_slash
  select_permissions:
  - role: public
    permission:
      columns:
      - block_number
      - event_index
      - account_id
      - amount
      - timestamp
      filter: {}
      allow_aggregations: true
- table:
    schema: public
    name: token_holder
  object_relationships:
  - name: contract
    using:
      manual_configuration:
        remote_table:
          schema: public
          name: contract
        column_mapping:
          contract_id: contract_id
  select_permissions:
  - role: public
    permission:
      columns:
      - contract_id
      - holder_account_id
      - holder_evm_address
      - balance
      - block_height
      - timestamp
      filter: {}
      allow_aggregations: true
- table:
    schema: public
    name: total
  select_permissions:
  - role: public
    permission:
      columns:
      - name
      - count
      filter: {}
      allow_aggregations: true
- table:
    schema: public
    name: transfer
  select_permissions:
  - role: public
    permission:
      columns:
      - block_number
      - extrinsic_index
      - section
      - method
      - hash
      - source
      - destination
      - amount
      - denom
      - fee_amount
      - success
      - error_message
      - timestamp
      filter: {}
      allow_aggregations: true
