name: reef-explorer Build & Publish

on:
  workflow_dispatch:
    inputs:
      services:
        description: 'What services would you like to build e.g. "graphql crawler"'
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: echo "VERSION=$(./resources/increment_version.sh .env)" >> $GITHUB_ENV
      - run: make net=mainnet env=prod cmd=build services=${{ github.event.inputs.services }} execute
      - run: make net=mainnet env=prod cmd=push services=${{ github.event.inputs.services }} execute
      - if: github.ref == 'refs/heads/develop'
        run: |
          git config --global user.name 'frisitano'
          git config --global user.email 'francesco.risitano95@gmail.com'
          git tag ${VERSION}
          git add -u
          git commit -m "New release ${VERSION}"
          git push
          git push --tags
